
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dev_db?useTimezone=true&serverTimezone=UTC
    username: root
    password: Mysql123@
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
      show-sql: false
springdoc:
  pathsToMatch: /api/**/v1/**
  swagger-ui:
    use-root-path: true